/* eslint-disable eol-last */
export const ThirdPartyActionTypes = {
    API_KEY_FETCH_REQUEST: 'ES/API_KEY_FETCH_REQUEST',
    API_KEY_FETCH_SUCCESS: 'ES/API_KEY_FETCH_SUCCESS',
    API_KEY_FETCH_ERROR: 'ES/API_KEY_FETCH_ERROR',
    API_KEY_LIST: 'ES/API_KEY_LIST',
    API_KEY_DETAILS: 'ES/API_KEY_DETAILS',
    API_KEY_ADD_SUCCESS: 'ES/API_KEY_ADD_SUCCESS',
    API_KEY_NETWORK_CALL_UPDATE: 'ES/API_KEY_NETWORK_CALL_UPDATE '
}

export const UserActionTypes = {
    USER_DETAILS: 'ES/USER/USER_DETAILS',
    UPDTAE_USER_DETAILS: 'ES/USER/UPDTAE_USER_DETAILS',
    CURRENT_USER_DETAILS: 'ES/CURRENT_USER_DETAILS',
    USER_NETWORK_CALL_UPDATE: 'ES/USER_NETWORK_CALL_UPDATE',
    USER_LIST: 'ES/USER/USER_LIST',
    USER_ID_LIST: 'ES/USER_ID_LIST',
    USER_LOGIN: 'ES/USER_LOGIN',
    USER_LOGOUT: 'ES/USER_LOGOUT',
    USER_PRIVILEGE_ROLE: 'ES/USER_PRIVILEGE_ROLE',
    DEVICE_LIMIT: 'ES/DEVICE_LIMIT'
}

export const OrganizationActionTypes = {
    ORG_LIST_FETCH_REQUEST: 'ES/ORG_LIST_FETCH_REQUEST',
    ORG_LIST_FETCH_SUCCESS: 'ES/ORG_LIST_FETCH_SUCCESS',
    ORG_LIST_FETCH_ERROR: 'ES/ORG_LIST_FETCH_ERROR',
    ORG_LIST: 'ES/ORG_LIST',
    ORG_DETAILS: 'ES/ORG_DETAILS',
    ORG_DETAILS_FETCH_REQUEST: 'ES/ORG_DETAILS_FETCH_REQUEST',
    ORG_LIST_ADD_SUCCESS: 'ES/ORG_LIST_ADD_SUCCESS',
    ORG_IDS: 'ES/ORG_IDS'
}

export const DiagnosticsActionTypes = {
    DEVICE_ERROR_LIST: 'ES/DEVICE_ERROR_LIST',
    DEVICE_NETWORK_CALL_UPDATE: 'ES/DEVICE_NETWORK_CALL_UPDATE'
}

export const DeviceActionTypes = {
    DEVICE_STATISTICS_DATA: 'ES/DEVICE_STATISTICS_DATA',
    DEVICE_LIST: 'ES/DEVICE/LIST',
    DEVICE_FETCH_REQUEST: 'ES/DEVICE/FETCH/REQUEST',
    DEVICE_DETAILS: 'ES/DEVICE/DETAILS',
    DEVICE_ID_LIST: 'ES/DEVICE_ID_LIST',
    DEVICE_DATA_LOADING: 'ES/DEVICE_DATA_LOADING',
    DEVICE_PARAM_LIST: 'ES/DEVICE/SENSOR/PARAM/LIST'
}

export const AlarmActionTypes = {
    ALARM_NETWORK_CALL_UPDATE: 'ES/ALARM_NETWORK_CALL_UPDATE',
    ALARM_LIST: 'ES/ALARM_LIST',
    ALARM_DETAILS: 'ES/ALARM_DETAILS',
    ALARM_ADD_SUCCESS: 'ES/ALARM_ADD_SUCCESS',
    ALARM_RULE_FETCH_REQUEST: 'ES/ALARM_RULE_FETCH_REQUEST',
    ACTIVE_ALARM_LIST: 'ES/ACTIVE_ALARM_LIST',
    ALARM_HISTORY_LIST: 'ES/ALARM_HISTORY_LIST'
}

export const SensorActionTypes = {
    SENSOR_TYPE_LIST: 'ES/SENSOR/TYPE/LIST',
    SENSOR_PARAM_LIST: 'ES/SENSOR/PARAM/LIST',
    SENSOR_PARAM_ID_LIST: 'ES/SENSOR/PARAM/ID/LIST',
    SENSOR_TYPE_ID_LIST: 'ES/SENSOR/TYPE/ID/LIST',
    SENSOR_TYPE_DETAILS: 'ES/SENSOR/TYPE/DETAILS'
}

export const DashboardActionTypes = {
    DASHBOARD_STATISTICS: 'ES/DASHBOARD_STATISTICS',
    DASHBOARD_SELECTED_DEVICE: 'ES/DASHBOARD_SELECTED_DEVICE'
}

export const CalibrationActionTypes = {
    CALIB_NETWORK_CALL_UPDATE: 'ES/CALIB_NETWORK_CALL_UPDATE',
    CALIB_LIST: 'ES/CALIB_LIST',
    CALIB_ADD_SUCCESS: 'ES/CALIB_ADD_SUCCESS'
}

export const WebhookActionTypes = {
    WEBHOOK_LIST: 'ES/WEBHOOK_LIST',
    WEBHOOK_ADD_SUCCESS: 'ES/WEBHOOK_ADD_SUCCESS',
    WEBHOOK_DETAILS: 'ES/WEBHOOK_DETAILS'
}

export const PreferenceActionTypes = {
    PREFERENCE_LIST: 'ES/PREFERENCE_LIST',
    PREFERENCE_LIST_FETCHING: 'ES/PREFERENCE_LIST_FETCHING'
}